### PR TITLE
Compact the output of feature_gcode by using a variable instead of repeating each extrusion_role individually

### PR DESCRIPTION
**Pull request by kesor**

### CODE REVIEW

**Comment by AndrewEllis93** [comment]
Hi, 

I like the line breaks - though it's more of a stylistic choice than functional. 
It makes it easier for me to read rather than one monolithic wall of text. 

That said, I did take your slightly shorter if/elsif statements, they seem to be working, so I will likely incorporate that:

```
; External perimeter
{if extrusion_role=~/ExternalPerimeter/}
SET_VELOCITY_LIMIT ACCEL=1000 ACCEL_TO_DECEL=500 SQUARE_CORNER_VELOCITY=8

; Perimeter
{elsif extrusion_role=~/Perimeter/}
SET_VELOCITY_LIMIT ACCEL=2000 ACCEL_TO_DECEL=1000 SQUARE_CORNER_VELOCITY=8

; Overhang perimeter
{elsif extrusion_role=~/OverhangPerimeter/}
SET_VELOCITY_LIMIT ACCEL=2000 ACCEL_TO_DECEL=1000 SQUARE_CORNER_VELOCITY=8

; Overhang perimeter
{elsif extrusion_role=~/InternalInfill/}
SET_VELOCITY_LIMIT ACCEL=7000 ACCEL_TO_DECEL=3500 SQUARE_CORNER_VELOCITY=8

; Top solid infill
{elsif extrusion_role=~/TopSolidInfill/}
SET_VELOCITY_LIMIT ACCEL=2000 ACCEL_TO_DECEL=1000 SQUARE_CORNER_VELOCITY=8

; Solid infill
{elsif extrusion_role=~/SolidInfill/}
SET_VELOCITY_LIMIT ACCEL=4000 ACCEL_TO_DECEL=2000 SQUARE_CORNER_VELOCITY=8

; Bridge infill
{elsif extrusion_role=~/BridgeInfill/}
SET_VELOCITY_LIMIT ACCEL=5000 ACCEL_TO_DECEL=2500 SQUARE_CORNER_VELOCITY=8

; Gap fill
{elsif extrusion_role=~/GapFill/}
SET_VELOCITY_LIMIT ACCEL=2000 ACCEL_TO_DECEL=1000 SQUARE_CORNER_VELOCITY=8

; Skirt
{elsif extrusion_role=~/Skirt/}
SET_VELOCITY_LIMIT ACCEL=7000 ACCEL_TO_DECEL=3500 SQUARE_CORNER_VELOCITY=8

; Support material
{elsif extrusion_role=~/SupportMaterial/}
SET_VELOCITY_LIMIT ACCEL=7000 ACCEL_TO_DECEL=3500 SQUARE_CORNER_VELOCITY=8

; Support material interface
{elsif extrusion_role=~/SupportMaterialInterface/}
SET_VELOCITY_LIMIT ACCEL=7000 ACCEL_TO_DECEL=3500 SQUARE_CORNER_VELOCITY=8

; Thin walls
{elsif extrusion_role=~/ThinWall/}
SET_VELOCITY_LIMIT ACCEL=2000 ACCEL_TO_DECEL=1000 SQUARE_CORNER_VELOCITY=8

; Other / catch-all
{else}
SET_VELOCITY_LIMIT ACCEL=4444 ACCEL_TO_DECEL=2222 SQUARE_CORNER_VELOCITY=8
{endif}
```

Hopefully this won't even be necessary soon. [The PR to make this native was just merged to the dev branch.](https://github.com/supermerill/SuperSlicer/pull/1858)

**Comment by eduncan911** [comment]
Fjrusjdigndn sndjdksm

**Comment by AndrewEllis93** [comment]
Modified feature gcode

**Comment by AndrewEllis93** [comment]
Maybe I misunderstood then. So with the code block I posted earlier, it just needs that `; [extrusion_role]` at the top?
(I basically took this from Stephan's profile, so I can't say I know exactly how it works)

**Comment by AndrewEllis93** [comment]
If you can update that code block I posted, I can try it out again

**Pull request closed without merging**
